### ISSUE TITLE
Automatic NATS creation for siddhi

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#24]
**Description:**
Siddhi operator currently supports for basic siddhi app deployments like HTTP. The failover deployment scenario of the siddhi operator should depend on with NATS or KAFKA. In that scenario, the user can specify a NATS configuration using the CR YAML file like below.

```
messaging.system:
  type: nats
  config:
    cluster.id: siddhi-nats
    bootstrap.servers: nats://siddhi-nats:4222
```
However it's much better to make this configuration optional and whenever user did not specify this, the siddhi operator will create the NATS cluster and the NATS streaming cluster automatically. That feature will give better user experience.

**Suggested Labels:**
type/new-feature
