### ISSUE TITLE
PVC creation support

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#26]
**Description:**
In the failover deployment scenario, the siddhi applications should maintain the persistence in two levels.

1. Messaging system (NATS/KAFKA)
1. Siddhi application level

The messaging system level persistence will handle by NATS or KAFKA. In order to handle siddhi application level persistence, siddhi app deployment needs a persistence volume. The creation of PV is an infrastructure configuration. Therefore the user should have to create a PV manually. However, the creation of PVC and bound it to the deployment pod can be done by siddhi operator. 

To do that user can specify PV configurations like below and relevant PVC should be created by the siddhi operator according to this configs.

```
persistence.volume:
  access.modes:
    - ReadWriteOnce
  volume.mode: Filesystem
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
```

**Suggested Labels:**
type/new-feature
