### ISSUE TITLE
Change CRD Pod Spec

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#29]
**Description:**

Previously in the 0.1.1 version siddhi operator had a spec called pod to retrieve docker image information like below.

```
pod: 
  image: siddhiio/siddhi-runner-alpine
  imagePullSecret: siddhi-secret
  imageTag: "0.1.0"
```
Since this specifications used to create the container it is better to have default k8s `container` spec instead of using `pod` spec like below.

```
container: 
  env: 
    - 
      name: RECEIVER_URL
      value: "http://0.0.0.0:8080/example"
    - 
      name: BASIC_AUTH_ENABLED
      value: "false"
    - 
      name: NATS_URL
      value: "nats://siddhi-nats:4222"
    - 
      name: NATS_DEST
      value: siddhi
    - 
      name: NATS_CLUSTER_ID
      value: siddhi-stan
  image: "buddhiwathsala/siddhi-runner:0.1.1"

```
But this container spec does not contain `imagePullSecret` spec we need to have a separate spec to get image pull secret. 

**Suggested Labels:**

Improvement
