### ISSUE TITLE
Adding New Spec to the Failover Deployment

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#30]
**Description:**
For the failover deployment of the siddhi-operator, we need a messaging layer and PV configurations to be specified in the CRD. So it is better to have specs like below.

```
messagingSystem: 
  type: nats
  bootstrapServers: 
    - "nats://siddhi-nats:4222"
  clusterId: siddhi-stan

persistentVolume: 
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 8Gi
  storageClassName: slow
  type: nats
  volumeMode: Filesystem
```
### Notes

- If the user specified multiple siddhi apps to be deployed in failover mode, siddhi operator will use the same PV configuration to create PVCs for each kubernetes deployment.
- If the user only specified the `messagingSystem` as below siddhi operator will automatically create NATS cluster and streaming cluster and deployed the failover mode.
```
messagingSystem: 
  type: nats
```
- Providing `massagingSystem` as above is an indication to the siddhi-operator to deploy siddhi apps in failover mode(HA mode). 
- Also the failover mode is really similar to distributed deployment mode in siddhi with `replication factor = 1` in all partial apps.

**Suggested Labels:**
