### ISSUE TITLE
Deployment config read as YAML instead of a string

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#32]
**Description:**
Currently, the custom object of siddhi operator reads the configurations that need to change at the siddhi runner level using a string as below.
```
siddhi.runner.configs: |-
    state.persistence:
      enabled: true
      intervalInMin: 1
      revisionsToKeep: 2
      persistenceStore: io.siddhi.distribution.core.persistence.FileSystemPersistenceStore
      config:
        location: siddhi-app-persistence
```
It is much better to have direct YAML reading instead of this string. In order to enable that YAML reading, we have to read arbitrary YAML in operator level. 

In golang, we normally [read arbitrary JSON objects](https://stackoverflow.com/questions/33436730/unmarshal-json-with-unknown-fields) using structures like below.

```
map[string]interface{}
```

But because of [this](https://github.com/operator-framework/operator-sdk/issues/1624) issue in operator sdk, we are having a problem of reading an arbitrary YAML.

**Suggested Labels:**
type/bug

**Related Issues:**
https://github.com/operator-framework/operator-sdk/issues/1624
