### ISSUE TITLE
Appending rules to the ingress instead of updating HTTP paths

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#43]
**Description:**
When we deploy SiddhiProcesses which has HTTP sources ingress will automatically create and add rules. That ingress use hostname as `siddhi`. But when we deploy several SiddhiProcesses with HTTP sources, that ingress will add multiple rules to the ingress as below.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: siddhi
  namespace: default
spec:
  rules:
  - host: siddhi
    http:
      paths:
      - backend:
          serviceName: nats-app-0
          servicePort: 8080
        path: /nats-app-0/8080/
  - host: siddhi
    http:
      paths:
      - backend:
          serviceName: nats-app1-0
          servicePort: 8080
        path: /nats-app1-0/8080/
```
Here siddhi-operator add multiple rules with siddhi hostname. But it is better to add paths under the same host without replicating rules like below.

```
spec:
  rules:
  - host: siddhi
    http:
      paths:
      - backend:
          serviceName: nats-app-0
          servicePort: 8080
        path: /nats-app-0/8080/
      - backend:
          serviceName: nats-app1-0
          servicePort: 8080
        path: /nats-app1-0/8080/
```

**Suggested Labels:**
Improvement

**Affected Product Version:**
Siddhi operator 0.1.0 - 0.2.0-m1

**Steps to reproduce:**
1. Install siddhi operator 
1. Install two SiddhiProcesses which has HTTP source.
