### ISSUE TITLE
Changing messaging system specs to camel case

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#47]
**Description:**
In the previous 0.2.0-m1 release, the messaging system spec had some specs which follow dot naming convention. 
```yaml
  messagingSystem:
    type: nats
    config: 
      bootstrap.servers: 
        - "nats://siddhi-nats:4222"
      cluster.id: siddhi-stan
```

This should change like below.

```yaml
  messagingSystem:
    type: nats
    config: 
      bootstrapServers: 
        - "nats://nats-siddhi:4222"
      clusterID: stan-siddhi
```

**Suggested Labels:**
type/improvement
