### ISSUE TITLE
Change PV and messaging system configs

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#82]
**Description:**
Previously, we have to specify the persistent volume configuration as below in SiddhiProcess.
```yaml
  persistentVolume: 
    accessModes: 
      - ReadWriteOnce
    resources: 
      requests: 
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
```
Actually, these configs will be used to create the PVC inside the Siddhi operator. Hence, it should change as below.

```yaml
  persistentVolumeClaim: 
    accessModes: 
      - ReadWriteOnce
    resources: 
      requests: 
        storage: 1Gi
    storageClassName: standard
    volumeMode: Filesystem
```

Also in the messaging system, we get the cluster-ID as an input. That cluster-ID should be the cluster-ID of the streaming cluster. Since NATS have two cluster types(NATS cluster and streaming cluster) it would be better to differentiate in the spec itself like below.

```yaml
  messagingSystem:
    type: nats
    config: 
      bootstrapServers: 
        - "nats://nats-siddhi:4222"
      streamingClusterId: stan-siddhi
```

**Suggested Labels:**
Feature improvement

**Affected Product Version:**
0.2.0-m2
