### ISSUE TITLE
Adding Siddhi runner spec change to the documentation

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-operator#88]
**Description:**
Add the $subject to the [siddhi.io](https://siddhi.io) documentation under the section https://siddhi.io/en/v5.1/docs/siddhi-as-a-kubernetes-microservice/.

For example: Change state persistence config use following block in K8s YAML.
```yaml
  runner: |
    state.persistence:
      enabled: true
      intervalInMin: 1
      revisionsToKeep: 2
      persistenceStore: io.siddhi.distribution.core.persistence.FileSystemPersistenceStore
      config:
        location: siddhi-app-persistence
```
